name: "js_marketing_dbt_cl"
version: "2.1.0"
config-version: 2

profile: "default"
require-dbt-version: [ ">=1.6.0", "<2.0.0" ]

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "jaffle-data" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"
  "dbt_date:time_zone": "America/Los_Angeles"


query-comment:
  comment: "{{ common.query_comment(node) }}"
  job-label: True


quoting:
  database: true
  schema: true
  identifier: true

models:
  js_marketing_dbt_cl:
    staging:
      +materialized: table
    datamart:
      +materialized: table